Repository mcpcpc/kirc, pull requests merged in 2020-10, with the labels that each got.

#50 change -W to automatic wrap
  README.md
  kirc.1
  kirc.c
Labels: enhancement

#54 0.1.4
  .github/example.png
  .github/example2.png
  README.md
  kirc.c
Labels: enhancement

#55 seo activities
  .github/example4.png
  .github/tty.gif
  README
Labels: enhancement

#57 Fix Out-of-bound read
  kirc.c
Labels: bug

#60 0.1.5
  kirc.c
Labels: enhancement

#63 0.1.6
  README
  kirc.1
  kirc.c
Labels: enhancement

#68 0.1.7
  README
  kirc.c
Labels: enhancement

#71 0.1.8
  kirc.c
Labels: bug

#75 man page: remove forward slash reference
  kirc.1
Labels: bug

#86 0.2.0
  kirc.c
Labels: bug

#89 CTRL+A and CTRL+E are swapped in the README
  README
Labels: documentation
