Repository mcpcpc/kirc, pull requests merged in 2020-09, with the labels that each got.

#19 Add error handling to irc_init
  kirc.c
Labels: enhancement

#33 Add alias PRIVMSG aliased command
  README.md
  kirc.c
Labels: enhancement

#36 add check for fgets value
  kirc.c
Labels: bug

#40 add additional highlighting
  kirc.c
Labels: enhancement

#42 Support SASL EXTERNAL
  kirc.c
Labels: enhancement

#44 add SASL EXTERNAL example
  README.md
Labels: documentation, enhancement

#46 add manpage
  Makefile
  kirc.1
  kirc.c
Labels: enhancement

#47 README improvements
  .github/example4.png
  README.md
Labels: documentation
